[package]
name = "lisp"
version = "0.1.0"
authors = ["TurtlePU <sokolov.p64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "7.1.0"
nom = "6"
